import fiftyone as fo
import fiftyone.zoo as foz

dataset = fo.zoo.load_zoo_dataset(
    "open-images-v7",
    label_types=["detections"],
    classes=[
        "Brown bear",
        # "Panda",
        # "Polar bear",
        # "Cat",
        # "Fox",
        # "Jaguar",
        # "Lynx",
        # "Red panda",
        # "Tiger",
        # "Lion",
        "Dog",
        # "Leopard",
        # "Cheetah",
        # "Raccoon",
        "Camel",
        "Cattle",
        # "Giraffe",
        # "Rhinoceros",
        "Goat",
        "Horse",
        # "Hamster",
        # "Kangaroo",
        # "Koala",
        # "Mouse",
        "Pig",
        # "Rabbit",
        # "Squirrel",
        "Sheep",
        "Zebra",
        # "Monkey",
        # "Hippopotamus",
        "Deer",
        # "Elephant",
        # "Porcupine",
        # "Hedgehog",
        "Bull",
        "Antelope",
        "Mule",

        # "Bow and arrow",
        # "Cannon",
        # "Dagger",
        # "Knife",
        "Rifle",
        "Shotgun",
        # "Axe",
        # "Handgun",
        # "Sword",
        # "Missile",
        # "Bomb",

        # "Car",
        # "Taxi",
        # "Bus",
        # "Snowmobile",
        # "Golf cart",
        # "Motorcycle",
        # "Segway",
        # "Tank",
        # "Truck",
        # "Limousine",
        # "Van",

        # "Girl",
        # "Woman",
        # "Man",
    ],
    max_samples=100,
)
session = fo.launch_app(dataset)
session.wait()
